/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalconsultorio;

/**
 *
 * @author sluar
 */
public class sistema extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public sistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();
        menLoging = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menGestionConsultorios = new javax.swing.JMenuItem();
        menGestionMedicos = new javax.swing.JMenuItem();
        menGestionPacientes = new javax.swing.JMenuItem();
        menGestionUsuarios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Archivo");

        mnuSalir.setText("Salir ");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSalir);

        menLoging.setText("Login");
        menLoging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menLogingActionPerformed(evt);
            }
        });
        jMenu1.add(menLoging);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Gestion");

        menGestionConsultorios.setText("Gestión Consultorios");
        menGestionConsultorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menGestionConsultoriosActionPerformed(evt);
            }
        });
        jMenu2.add(menGestionConsultorios);

        menGestionMedicos.setText("Gestión Medicos");
        menGestionMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menGestionMedicosActionPerformed(evt);
            }
        });
        jMenu2.add(menGestionMedicos);

        menGestionPacientes.setText("Gestión Pacientes");
        menGestionPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menGestionPacientesActionPerformed(evt);
            }
        });
        jMenu2.add(menGestionPacientes);

        menGestionUsuarios.setText("Gestión Usuarios");
        menGestionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menGestionUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(menGestionUsuarios);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayudas");

        jMenuItem1.setText("Manual Usuario");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
     System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void menLogingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menLogingActionPerformed
       Login login = new Login ();
       login.setVisible(true);
       this.setVisible(false);
       
    }//GEN-LAST:event_menLogingActionPerformed

    private void menGestionConsultoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menGestionConsultoriosActionPerformed
    GestionConsultorios consultorios = new GestionConsultorios ();
    consultorios.setVisible(true);
    }//GEN-LAST:event_menGestionConsultoriosActionPerformed

    private void menGestionMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menGestionMedicosActionPerformed
      GestinoMedicos medicos = new GestinoMedicos ();
    medicos.setVisible(true);
    }//GEN-LAST:event_menGestionMedicosActionPerformed

    private void menGestionPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menGestionPacientesActionPerformed
       GestionPacientes pacientes = new GestionPacientes ();
    pacientes.setVisible(true);
    }//GEN-LAST:event_menGestionPacientesActionPerformed

    private void menGestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menGestionUsuariosActionPerformed
    GestionUsuarios usuarios= new GestionUsuarios ();
    usuarios.setVisible(true);
    }//GEN-LAST:event_menGestionUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menGestionConsultorios;
    private javax.swing.JMenuItem menGestionMedicos;
    private javax.swing.JMenuItem menGestionPacientes;
    private javax.swing.JMenuItem menGestionUsuarios;
    private javax.swing.JMenuItem menLoging;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
